spring.application.name=TrabalhoLucas

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.aomgxbebsecyyjycwqei
spring.datasource.password=familiamlln04

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true