create table tb_suatendimento (
    id bigint generated by default as identity primary key,

    paciente_id bigint not null,
    profissional_id bigint not null,

    data_hora timestamp not null,

    tipo varchar(255) not null,

    status varchar(255) not null,

    diagnostico text,

    observacoes text,

    valor double precision,

    constraint fk_atendimento_paciente foreign key (paciente_id) references tb_supaciente(id),
    constraint fk_atendimento_profissional foreign key (profissional_id) references tb_suprofissional(id)
);
