package com.OsGuri.TrabalhoLucas.especialidade;

public enum EspecialidadeEnum {
    CLINICA_MEDICA,
    PEDIATRIA,
    CIRURGIA_GERAL,
    GINECOLOGIA_E_OBSTETRICIA,
    MEDICINA_DO_TRABALHO,
    ORTOPEDIA_E_TRAUMATOLOGIA,
    CARDIOLOGIA,
    OFTALMOLOGIA,
    PSIQUIATRIA,
    DERMATOLOGIA,
    MEDICINA_INTENSIVA,
    RADIOLOGIA_E_DIAGNOSTICO_POR_IMAGEM,
    OTORRINOLARINGOLOGIA,
    UROLOGIA,
    ENDOCRINOLOGIA,
    NEUROLOGIA,
    CIRURGIA_PLASTICA,
    GASTROENTEROLOGIA,
    ONCOLOGIA
}
