create table tb_supaciente (
    id bigint generated by default as identity primary key,

    ativo boolean not null default true,

    nome_completo varchar(255) not null,

    cpf varchar(14) not null unique,

    data_nascimento timestamp not null,

    sexo varchar(20) not null,

    telefone varchar(20) not null,

    email varchar(255) not null unique,

    endereco varchar(255) not null,

    convenio varchar(255) not null,

    numero_carteirinha varchar(100) not null unique
);