create table tb_suprofissional (
    id bigint generated by default as identity primary key,

    ativo boolean not null default true,

    nome varchar(255) not null,

    registro_conselho varchar(255) not null unique,

    especialidade_id bigint not null,

    cargo varchar(255) not null,

    turno varchar(255) not null,

    telefone varchar(255) not null,

    email varchar(255) not null unique
);
