create table tb_suespecialidade (
    id bigint generated by default as identity primary key,

    ativo boolean not null default true,

    nome varchar(255) not null unique,

    descricao varchar(255) not null,

    area varchar(255) not null
);

alter table tb_suprofissional
    add constraint fk_tb_suprofissional_especialidade foreign key (especialidade_id) references tb_suespecialidade(id);
